### ISSUE TITLE
Discuss what to display for empty recent/popular links

### ISSUE THREAD

**Issue by SterlingVelazquez** [SterlingVelazquez/TabdaT#52]
When there are no recent or popular links displayed in the hotbar (presumably because a user hasn't clicked on a link yet), a message should be shown in the blank space below the hotbar icon explaining what that section is for.

**Comment by galexander17** [comment]
Tried to design a blur on blur neumorphic design, but its not working the way I wanted to. Unable to come up with a design alternative that works for all themes. Stick to just the icons for now.
