### ISSUE TITLE
Discuss how to handle hotbar when user is not signed in

### ISSUE THREAD

**Issue by SterlingVelazquez** [SterlingVelazquez/TabdaT#53]
When not signed in, the recent/popular hotbar sections do not display any links. Users who haven't signed in should be given some kind of indication that they need to be signed in to access that feature.

**Comment by galexander17** [comment]
When not signed in, the user can click on the most recent or most popular options in the hotbar - but there will be a text saying: "Sign in to Google to unlock this feature". Same message for both

**Comment by galexander17** [comment]
Bolden the word "Sign In" and have the user only click the Sign In text - to prevent accidentally clicking the entire text, and the user signing in, when they may not want to sign in
